### PR TITLE
Pla 711 create panel component

### PR DESCRIPTION
**Pull request by rodelta**
## Description

Adds a dedicated component for the Panel. 

Updates prettier and its tailwind plugin, with some config, so it sorts the classes on save.

Marked `Section.Panel` as deprecated. 
I found uses in v2 and on Portal. In some cases, only the Panel was used. Since the Panel is simple and Atomic, it should take precedence over having it tied to another component. The deprecation is for internal reference, shouldn't affect any build that uses it.

The plugin set up raised some eslint errors due to unordered classes, so fixed those.

Also fixed some long-standing linter warning about using one "any" prop

## Checklist

- [ ] Change increases quality
- [ ] Change is validated by tests
- [ ] Change is readable and easy to understand
- [ ] Documentation is updated
- [ ] Security impact has been considered
- [ ] Changes validated in runtime

### CODE REVIEW

**Comment by mnlfischer** [comment]
To remove the Panel is also a benefit to reduce the misuse of a panel without the section surrounding itself.

**Comment by mnlfischer** [comment]
I would like to see a corresponding Figma component to be in sync. It looks like the panel will be widely used and we should secure us for doing mistakes when we changed it for so many references.

**Comment by rodelta** [comment]
I got a response from UX. 
> it wouldn’t get added to Figma as it works differently on the design side. It’s just styles applied to a frame. The frame itself wouldn’t be a component.
> Components don’t work exactly the same in design and code. This is an example of something that shouldn’t be a component in design, just Styles.
> In the end, same results, meaning when we use a frame, you already know you can pick up that component and it’ll match the styling.i wish I could also pick it up as a component but since the inner content varies, I’d have to detach it each time. Design components don’t allow for choosing the children later on, like the dev components can.

I checked hailstorm, and we have several components that are not in Figma, so if we take this argument we're not breaking previous consistency. I imagine we might want to make the case for having a clear rule, but I would consider this OOS for the context of this PR.

**Comment by mnlfischer** [comment]
> I got a response from UX.
> 
> > it wouldn’t get added to Figma as it works differently on the design side. It’s just styles applied to a frame. The frame itself wouldn’t be a component.
> > Components don’t work exactly the same in design and code. This is an example of something that shouldn’t be a component in design, just Styles.
> > In the end, same results, meaning when we use a frame, you already know you can pick up that component and it’ll match the styling.i wish I could also pick it up as a component but since the inner content varies, I’d have to detach it each time. Design components don’t allow for choosing the children later on, like the dev components can.
> 
> I checked hailstorm, and we have several components that are not in Figma, so if we take this argument we're not breaking previous consistency. I imagine we might want to make the case for having a clear rule, but I would consider this OOS for the context of this PR.

Yes we have some components, especially the Layout components are missing in the Figma file because it is seemingly hard to create components with dynamic childs. If we stick with the figma effects/styles, we need to define any communication process.

**Pull request merged**
